<?php 
$arrayNama = array(
    "Mochammad Imania",
    "Agus Risyad",
    "Adam Sherina",
    "Fauzi Tiara",
    "Deka Bisri",
    "Dimas Aristy",
    "Dee Zakia",
    "Aulia Noor",
    "Finaldi Pambudi",
    "Chaerul Adam Dinantika",
    "Ari Izhar",
    "Rezky Daniel Bertauli",
    "Andhicha Rosmalia",
    "Bob Mawarni",
    "Irsan Michael Suheryanto",
    "Ficky Bryan Yuliasti",
    "Yosafat Novitasari",
    "Andrie S",
    "Anas Haq",
    "Bintang Ardina",
    "Ferdiansyah Cahyani",
    "Sebastian Sigit Ulfania",
    "Satrya Maulidah",
    "Rian Ari Maulinda",
    "Fahlian Izhar Prayogi",
    "Mark Zahra",
    "Devito Fatimah",
    "Alditio Dewi",
    "Abdullah Sinuka",
    "Mirza Falah",
    "Hizkia Julianto",
    "Naufal Mario Puspa",
    "Edy Astuti",
    "Ryan Anisa",
    "Aprian Naenggolan",
    "Nauval Rizkia",
    "Haikal Rompas",
    "Romario Ryan Usra",
    "Revi Tursia",
    "Arthur Chandra",
    "Ramanta Larashaty",
    "Azrul Ramanta Indriani",
    "Hudzaifah Rafles",
    "Ekka Varensia",
    "Surya Agustina",
    "Firdaus Lukman Lestari",
    "Pandu Amelia",
    "Fariz Sulistyaningra",
    "Syahid Rahman",
    "Aristyo Defri");
shuffle($arrayNama);
$nama = $arrayNama[0];
?>