<?php
 $arrayPerusahaan = array(
        "Misung Industrial, PT/Misung Indonesia P",
        "Red Ribbon Indonesia",
        "Naga Mas Perkasa, PT",
        "Wirontono Cold Storage &industri PT",
        "Mahera Cv",
        "Incap Altin Utama/Incap Seno, PT",
        "Indomaguro Tunas Unggul",
        "Winner Synthetic Textil, PT",
        "Asata Utama Electrical Industries, PT",
        "Sinar Electronica Seb, PT",
        "Incap Altin Utama/Incap Seno, PT",
        "Indomaguro Tunas Unggul",
        "Winner Synthetic Textil, PT",
        "Asata Utama Electrical Industries, PT",
        "Sinar Electronica Seb, PT",
        "Paramategak Beton Indonesia, PT",
        "Cifico",
        "Hisotex PT",
        "Southern Cross Textile Industry PT",
        "Beta Concrit Mixerindo",
        "Firma (Bagan Harapan) Pesing, Fa",
        "Saudara ( Surono )",
        "Bogasari Flour PT/Indofood Sukses Makmur",
        "Ajid Temulawak",
        "Yasonta, PT (Sharp Electronics Ind)",
        "Kemakmuran Jakarta, CV",
        "Muroco, PT.",
        "Billy Gan /Bintang Mas",
        "Wahana Mulia Citra Tunggal, PT",
        "Narso Konfeksi Tas",
        "Bun Bun",
        "Continental Plastik/Continental Panjipra",
        "Sangra Ratu Gemilang",
        "Koperindo Reka Mandiri",
        "Fara Industri Tas");
    shuffle($arrayPerusahaan);
    $perusahaan = $arrayPerusahaan[0];
?>